### ISSUE TITLE
Some of the learn repos are not mainted/completed 

### ISSUE THREAD

**Issue by sohilpandya** [dwyl/product-roadmap#2]
Hey Nelson! ❤️ the work you've put into the roadmap. 

I've got a couple of questions regarding a couple of the `learn` repos. 

- learn-blockchain
- learn-WebRTC
- learn-progressive-web-apps

These are not currently being actively maintained, Is it the case of people finding out about these and then working on them? or should we have more of a plan as to who maintains these?

**Comment by nelsonic** [comment]
@sohilpandya _good_ question. I've been working on https://github.com/dwyl/learn-blockchain on weekends and will have something to show _soon_ ..
@finnhodgkin & ZooeyMiller will be looking at both https://github.com/dwyl/learn-WebRTC and https://github.com/dwyl/learn-progressive-web-apps in the next couple of weeks. 
They are _currently_ looking at: https://github.com/dwyl/learn-offline-first 
which is _related_ to https://github.com/dwyl/learn-progressive-web-apps but _separate_ because it covers iOS.

We will be updating the Roadmap soon to reflect this. 👍

**Comment by nelsonic** [comment]
@sohilpandya let us know if your question is answered and if you have any other thoughts! 👍

**Comment by sohilpandya** [comment]
Thanks for the update. Happy to close the issue. 😊
