### ISSUE TITLE
What? section - should this be more detailed?

### ISSUE THREAD

**Issue by Cleop** [dwyl/product-roadmap#9]
As a team member working at dwyl
I want to have a clear understanding of the goals/direction of the company
So that I can ensure that my work/energy is being poured into where it is needed most.

I feel like the key points of 'what' the product roadmap is below:

> Communication
Personal Time Management
Teamwork
Life-long Learning
Nutrition, Health and Fitness
Personal Finance Management
Self-Actualisation

Are very broad and relate but don't capture entirely the works and ideas of projects that I've heard discussed in person or elsewhere on github for the dwyl team. I'm no expert on roadmaps but on a personal level I think I would find things clearer if perhaps they were a little more specific or detailed.

@nelsonic - is this as detailed as you intended to make the product roadmap? Or do you think we should build out this section more before we launch further into building the roadmap?

**Comment by nelsonic** [comment]
@Cleop _thank you_ for opening this issue/question. 
I _agree_ that it can be _difficult_ to _understand_ the goals/direction of the company.
We will be clarifying the product _together_ (_as a team_) over the next few days/weeks.
The _order_ of the "key points" in the What section is the order we will be approaching them.
We are building a "personal effectiveness" app.
It will allow people to "track any activity" so that people can analyse how they spend their time.
Managing your communications (_so you don't get interrupted when you're trying to focus_) 

If you or anyone else is ever in any doubt as to what they should pour their effort into,
use the simple heuristic: 
1. Finish the _current_ task that is  _assigned_ to you. 
2. Address any issues that are _assigned_ to you: e.g: https://github.com/issues?utf8=✓&q=is%3Aissue+is%3Aopen+assignee%3Anelsonic
1. Look at the "High Priority Help Wanted" issue list: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+org%3Adwyl+label%3Apriority-1+label%3A%22help+wanted%22
if there is something that you are _able_ to help with, dive in and help! Comment/contribute!
If you can _conclude/close_ an issue by _resolving_ it or because it's no longer time-relevant, do it!
2. **_Deliberately_ practice** and become _excellent_ at the "core" skills required: https://github.com/dwyl/technology-stack. (_you can never be "too good" at programming, UX or other creative work_) 
3. Read the books we have on the tech and any other relevant business/psychology/design/personal effectiveness books e.g:
    + Measure What Matters - https://www.amazon.com/Measure-What-Matters/dp/0525536221
    + Principles: Life and Work - https://www.amazon.com/Principals/dp/B071CTK28D
    + Checklist Manifesto - https://www.amazon.com/Checklist-Manifesto/dp/B0030V0PEW
    + To-Do List Formula - https://www.amazon.com/Todo-List-Formula/dp/B01JJ5CURW
    + Tools of Titans - https://www.amazon.com/Tools-of-Titans/dp/B01HSMRWNU
    + Lean Analytics - https://www.amazon.com/Lean-Analytics-Better-Startup/dp/1449335675
    + Essentialism: The Disciplined Pursuit of Less - https://www.amazon.com/dp/0804137382

All of these books are relevant to the _product_ we are building.
If we can "translate" the "Tools of Titans" into an App we will _automatically_ win.

**Comment by RobStallion** [comment]
@nelsonic Thanks for the response 👍

Only question I have (right now at least) is should we update this list to include the 'BLOCKED' label?

**Comment by nelsonic** [comment]
@RobStallion _good_ point. 💡 
The **`BLOCKED`** label (_discussed in https://github.com/dwyl/labels/issues/87 ..._) should only be applied in exceptionally rare circumstances and should be _automatic_. I have not included it (_above_) because we have not _agreed_ on the Label in the dicussion thread and as a result it has not been universally applied to all our repos/projects so it's not a going to be a _useful_ step (_yet_). 

> We currently only have _one_ "Blocked" issue https://github.com/dwyl/cid/issues/11 which has an associated PR: https://github.com/dwyl/cid/pull/21 which keeps getting "bounced" back to me and is still only 60% complete. There is _always_ a way that Docs/Examples can be improved. (_I know that sounds "harsh" and "open ended" ... but the CID module is **foundational** so the more we "polish" and make it "appetising" to people in the wider Elixir/IPFS community, so that they will use it, report bugs, request features and **contribute improvements** the better for both the short-term and long term of of the module, you as a "senior developer", the company and the community_) 
CID is an "entry point" re-useable module that we will be featuring in our _beginner_ tutorials.
Any doubt/confusion that a _beginner_ may have when they _first_ encounter it needs to be _systematically addressed_. That might not be the task in the _current_ PR, but as I've said before, the PR can _always_ be better. Badges? Coverage? Hex Docs? Detailed Usage Example? Example App that _implements_ the module? 

We do not currently have an "alert" system within the company for "Blocked" issues but we will _need_ to create one ASAP so people can respond to high priority items (_even if it means "pausing" their current task_)

**Comment by Cleop** [comment]
I am going to understand @nelsonic's response to mean that you don't think we need to update the 'what' section of the readme and therefore this issue can be closed.

**Comment by nelsonic** [comment]
@Cleop the "_What_?" section of the Product Roadmap _absolutely_ needs to be updated.
Sadly, even though I _agree_ that it is a _high_ priority, I have not had the time to focus on it.
Again, _sadly_ other people have been _demanding_ my attention on _far_ less important topics.

I will get to this issue as soon as I have the time/headspace.

**Comment by nelsonic** [comment]
Finally found (_made_) the time to update the Product Roadmap! Please See: #13 📝

**Comment by nelsonic** [comment]
@cleop Thanks again for opening this issue. ❤️ 
Please see: https://github.com/dwyl/product-roadmap#what (_and confirm if it improves understanding_)
If anything is unclear or requires more detail, _please_ open more issues with specific questions.
Our objective is for the answers in the Product Roadmap to be "***stand alone***". 
i.e. _anyone_ (_we have never met before_) can read them an understand what we our goal & plan is. 
If _anything_ is unclear we have _failed_ and need to improve.
Specific questions will help us to get clarity. e.g: #17

**Comment by Cleop** [comment]
This updated version looks clear ✨
